export { assertNever } from "./assert-never.js";

export { formatEnvironmentDisplay } from "./environment-display.js";
export type { EnvironmentDisplayInfo } from "./environment-display.js";

export {
  buildPendingInteractionApprovalResolution,
  formatPendingInteractionApprovalResolutionOutcome,
  formatPendingInteractionCommandApprovalResolutionMessage,
  formatPendingInteractionFileChangeApprovalResolutionMessage,
  formatPendingInteractionPermissionResolutionMessage,
  formatPendingInteractionPermissionResolutionOutcome,
  formatPendingInteractionSubjectDetailLines,
  getPendingInteractionApprovalGrantedPermissions,
  isPendingInteractionCommandApprovalPositiveDecision,
  summarizePendingInteractionCommandActions,
  summarizePendingInteractionRequestedMacOsPermissions,
  summarizePendingInteractionRequestedPermissions,
  toGrantedPendingInteractionPermissions,
} from "./pending-interaction-formatting.js";
export { formatPendingInteractionSummary } from "./pending-interaction-presentation.js";
export type {
  FormatPendingInteractionSummaryArgs,
  PendingInteractionPresentationSurface,
} from "./pending-interaction-presentation.js";

export { durationToCompactString, timeAgo } from "./format-helpers.js";

export { extractErrorMessage, toRecord } from "./unknown-helpers.js";

export {
  buildCollapsedGroupedTimelineRows,
  buildExploringDetailLines,
  buildGroupedTimelineRows,
  buildTimelineAssistantStepSummary,
  buildTimelineAssistantStepSummaryLabel,
  buildTimelineRowActivityInfoMap,
  buildToolBundleDetailLines,
  buildToolBundleSummaryLabel,
  buildToolBundleSummaryParts,
  buildTurnSummaryParts,
  countUniqueChangedFiles,
  decodeRow,
  deriveThreadTitleFromInput,
  extractShellCommandFromString,
  extractThreadContextWindowUsage,
  fileChangeIdentity,
  fileNameFromPath,
  findLatestActivityMessageId,
  findLatestActivityRowId,
  formatCommandOutputText,
  formatDelegationSummary,
  formatExploringCountsLabel,
  formatExploringIntentLine,
  formatFileChangeName,
  formatTimelineAsText,
  formatTimelineAssistantStepSummary,
  formatToolBundleSummaryLabel,
  formatToolCallCommand,
  formatTurnSummaryCountLabel,
  getCommandExitCodeLine,
  getDelegationSummaryParts,
  getPermissionGrantDisplayStatus,
  getTimelineDisplayStatus,
  getTimelineDisplayStatusInfo,
  getVisibleCommandOutput,
  hasVisibleCommandOutput,
  isIgnoredNoiseType,
  isShellToolName,
  outputFromThreadEvent,
  shouldHighlightLatestActivity,
  shouldPreferOngoingLabelsForRow,
  summarizeChangedFileNames,
  summarizeExploringCounts,
  taskStatusGlyph,
  timelineDisplayStatusValues,
  TIMELINE_NOISE_EVENT_TYPES,
  toViewMessages,
  toViewProjection,
  toViewProjectionEntries,
  flattenProjectionMessages,
  flattenProjectionMessagesDeep,
  flattenViewMessagesDeep,
} from "@bb/thread-view";
export type {
  ChangedFileNamesSummary,
  DelegationSummaryParts,
  EventMeta,
  ExploringCounts,
  FormatTimelineOptions,
  GroupedTimelineRowsOptions,
  ThreadEventWithMeta,
  TimelineDisplayStatus,
  TimelineDisplayStatusInfo,
  TimelineDisplayStatusTone,
  TimelineFormat,
  TimelineRowActivityInfo,
  TimelineTextFormatOptions,
  TimelineAssistantStepSummary,
  ToolBundleSummaryParts,
  ToolIntentSummary,
  TurnSummaryParts,
} from "@bb/thread-view";
