export type { EmptyInput, Endpoint, Untyped } from "./common.js";
export { typedRoutes } from "@bb/hono-typed-routes";
export {
  TERMINAL_COLS_MAX,
  TERMINAL_DATA_MAX_BASE64_LENGTH,
  TERMINAL_DATA_MAX_BYTES,
  TERMINAL_ROWS_MAX,
} from "@bb/domain";
export {
  HOST_AUTH_FILE_NAME,
  HOST_ID_FILE_NAME,
  hostAuthStateSchema,
  normalizeServerUrl,
} from "./local-state.js";
export type { HostAuthState } from "./local-state.js";

export {
  createHostDaemonLocalClient,
  DEFAULT_HOST_DAEMON_LOCAL_BIND_HOST,
  DEFAULT_HOST_DAEMON_LOCAL_HEALTH_PATH,
  DEFAULT_HOST_DAEMON_LOCAL_HEALTH_VALUE,
  healthResponseSchema,
  hostPlatformSchema,
  openInTargetRequestSchema,
  PATHS_EXIST_MAX_PATHS,
  pathsExistRequestSchema,
  pathsExistResponseSchema,
  pickFolderResponseSchema,
  providerCliInstallActionKindSchema,
  providerCliInstallActionKindValues,
  providerCliInstallActionSchema,
  providerCliInstallCommandKindSchema,
  providerCliInstallCommandKindValues,
  providerCliInstallCompletedEventSchema,
  providerCliInstallErrorEventSchema,
  providerCliInstallEventSchema,
  providerCliInstallOutputEventSchema,
  providerCliInstallOutputStreamSchema,
  providerCliInstallOutputStreamValues,
  providerCliInstallRequestSchema,
  providerCliInstallSourceSchema,
  providerCliInstallSourceValues,
  providerCliInstallStartedEventSchema,
  providerCliKeySchema,
  providerCliKeyValues,
  providerCliStatusResponseSchema,
  providerCliStatusSchema,
  statusResponseSchema,
  workspaceOpenTargetCapabilitiesSchema,
  workspaceOpenTargetIdSchema,
  workspaceOpenTargetIdValues,
  workspaceOpenTargetSchema,
  workspaceOpenTargetsResponseSchema,
} from "./local.js";
export type {
  HealthResponse,
  HostDaemonLocalRoutes,
  HostDaemonLocalSchema,
  HostPlatform,
  OpenInTargetRequest,
  PathsExistRequest,
  PathsExistResponse,
  PickFolderResponse,
  ProviderCliInstallAction,
  ProviderCliInstallActionKind,
  ProviderCliInstallCompletedEvent,
  ProviderCliInstallEvent,
  ProviderCliInstallRequest,
  ProviderCliInstallSource,
  ProviderCliKey,
  ProviderCliStatus,
  ProviderCliStatusResponse,
  StatusResponse,
  WorkspaceOpenTarget,
  WorkspaceOpenTargetCapabilities,
  WorkspaceOpenTargetId,
  WorkspaceOpenTargetsResponse,
} from "./local.js";

export {
  BRANCH_LIST_LIMIT_MAX,
  BRANCH_LIST_QUERY_MAX_LENGTH,
  FILE_LIST_LIMIT_MAX,
  FILE_LIST_QUERY_MAX_LENGTH,
  HOST_DAEMON_COMMAND_TYPES,
  HOST_DAEMON_PROTOCOL_VERSION,
  environmentDestroyCommandSchema,
  environmentProvisionCommandSchema,
  hostDaemonCommandEnvelopeSchema,
  hostDaemonCommandResultReportSchema,
  hostDaemonCommandResultSchemaByType,
  hostDaemonCommandSchema,
  hostDaemonCommandTypeSchema,
  hostDaemonExecutionOptionsSchema,
  codexInferenceCompleteCommandSchema,
  isHostDaemonCommandType,
  shouldFlushEventsBeforeReportingCommandResult,
  hostPathEntryKindSchema,
  hostPathEntrySchema,
  hostListFilesCommandSchema,
  hostListPathsCommandSchema,
  hostListBranchesCommandSchema,
  hostListManagerTemplatesCommandSchema,
  managerTemplateSummarySchema,
  hostReadFileCommandSchema,
  hostReadFileRelativeCommandSchema,
  hostReadFileRelativeDotfilePolicySchema,
  hostWriteFileRelativeCommandSchema,
  hostDeleteFileRelativeCommandSchema,
  hostDeletePathRelativeCommandSchema,
  providerListCommandSchema,
  providerListModelsCommandSchema,
  replayCaptureGetCommandSchema,
  replayCaptureListCommandSchema,
  replayRunCommandSchema,
  threadRenameCommandSchema,
  threadStartCommandSchema,
  threadStopCommandSchema,
  turnSubmitCommandSchema,
  turnSubmitTargetSchema,
  codexVoiceTranscribeCommandSchema,
  workspaceCommitCommandSchema,
  workspaceDiffCommandSchema,
  workspaceSquashMergeCommandSchema,
  workspaceContextSchema,
  workspaceStatusCommandSchema,
} from "./commands.js";
export type {
  EnvironmentProvisionCommand,
  HostDaemonCommand,
  HostDaemonCommandEnvelope,
  HostDaemonCommandResult,
  HostDaemonCommandResultByType,
  HostDaemonCommandResultReport,
  HostDaemonCommandResultReportWithoutSession,
  HostDaemonCommandType,
  HostPathEntry,
  HostPathEntryKind,
  HostReadFileRelativeDotfilePolicy,
  ManagerTemplateSummary,
  TurnSubmitTarget,
  WorkspaceContext,
} from "./commands.js";

export {
  buildHostDaemonWebSocketAuthorizationHeader,
  buildHostDaemonWebSocketProtocols,
  createHostDaemonClient,
  hasHostDaemonWebSocketProtocol,
  hostDaemonEnrollRequestSchema,
  hostDaemonEnrollResponseSchema,
  hostDaemonActiveThreadSchema,
  hostDaemonCommandBatchSchema,
  hostDaemonCommandsQuerySchema,
  hostDaemonCommandResultResponseSchema,
  hostDaemonAppDataChangePayloadSchema,
  hostDaemonAppDataChangeRequestSchema,
  hostDaemonAppDataResyncPayloadSchema,
  hostDaemonAppDataResyncRequestSchema,
  hostDaemonDaemonWsMessageSchema,
  hostDaemonEnvironmentChangePayloadSchema,
  hostDaemonEnvironmentChangeRequestSchema,
  hostDaemonEnvironmentChangeSchema,
  hostDaemonEventBatchRequestSchema,
  hostDaemonEventBatchResponseSchema,
  hostDaemonEventRejectionReasonSchema,
  hostDaemonInteractiveInterruptRequestSchema,
  hostDaemonInteractiveInterruptResponseSchema,
  hostDaemonInteractiveRequestResponseSchema,
  hostDaemonInteractiveRequestSchema,
  hostDaemonEventEnvelopeSchema,
  hostDaemonLoadedEnvironmentSchema,
  hostDaemonProjectAttachmentContentQuerySchema,
  hostDaemonRejectedEventSchema,
  hostDaemonServerWsMessageSchema,
  hostDaemonSessionCloseReasonSchema,
  hostDaemonSessionOpenRequestSchema,
  hostDaemonSessionOpenResponseSchema,
  hostDaemonTerminalOutputChunkSchema,
  hostDaemonTrackedThreadTargetSchema,
  hostDaemonToolCallRequestSchema,
  hostDaemonToolCallResponseSchema,
  HOST_DAEMON_WEBSOCKET_PROTOCOL,
} from "./session.js";
export type {
  HostDaemonActiveThread,
  HostDaemonCommandBatch,
  HostDaemonEnrollRequest,
  HostDaemonEnrollResponse,
  HostDaemonCommandsQuery,
  HostDaemonCommandResultResponse,
  HostDaemonAppDataChangePayload,
  HostDaemonAppDataChangeRequest,
  HostDaemonAppDataResyncPayload,
  HostDaemonAppDataResyncRequest,
  HostDaemonDaemonWsMessage,
  HostDaemonEnvironmentChange,
  HostDaemonEnvironmentChangePayload,
  HostDaemonEnvironmentChangeRequest,
  HostDaemonEventBatchRequest,
  HostDaemonEventBatchResponse,
  HostDaemonEventEnvelope,
  HostDaemonInteractiveInterruptRequest,
  HostDaemonInteractiveInterruptResponse,
  HostDaemonInteractiveRequest,
  HostDaemonInteractiveRequestResponse,
  HostDaemonInternalRoutes,
  HostDaemonInternalSchema,
  HostDaemonLoadedEnvironment,
  HostDaemonProjectAttachmentContentQuery,
  HostDaemonRejectedEvent,
  HostDaemonServerWsMessage,
  HostDaemonSessionCloseReason,
  HostDaemonSessionOpenRequest,
  HostDaemonSessionOpenResponse,
  HostDaemonTrackedThreadTarget,
  HostDaemonToolCallRequest,
  HostDaemonToolCallResponse,
} from "./session.js";
