import { HOST_DAEMON_PROTOCOL_VERSION } from "@bb/host-daemon-contract";
import {
  SANDBOX_DAEMON_HEALTH_PATH,
  SANDBOX_DAEMON_HEALTH_PORT,
} from "./constants.js";

function quote(value: string): string {
  return JSON.stringify(value);
}

export function buildFakeDaemonPayload(): string {
  return [
    'import { randomUUID } from "node:crypto";',
    'import { createServer } from "node:http";',
    "",
    `const healthPath = ${quote(SANDBOX_DAEMON_HEALTH_PATH)};`,
    `const healthPort = ${SANDBOX_DAEMON_HEALTH_PORT};`,
    `const protocolVersion = ${HOST_DAEMON_PROTOCOL_VERSION};`,
    "",
    "function requireEnv(name) {",
    "  const value = process.env[name]?.trim();",
    "  if (!value) {",
    '    throw new Error(`Missing required environment variable: ${name}`);',
    "  }",
    "  return value;",
    "}",
    "",
    "const hostId = requireEnv('BB_HOST_ID');",
    "const hostName = requireEnv('BB_HOST_NAME');",
    "const serverUrl = requireEnv('BB_SERVER_URL').replace(/\\/$/, '');",
    "const authToken = requireEnv('BB_SECRET_TOKEN');",
    "const maxConnectAttempts = Number(process.env.BB_DAEMON_CONNECT_MAX_ATTEMPTS ?? '30');",
    "const baseRetryMs = Number(process.env.BB_DAEMON_CONNECT_BASE_RETRY_MS ?? '1000');",
    "const maxRetryMs = Number(process.env.BB_DAEMON_CONNECT_MAX_RETRY_MS ?? '10000');",
    "",
    "function sleep(ms) {",
    "  return new Promise((resolve) => setTimeout(resolve, ms));",
    "}",
    "",
    "async function openSession() {",
    "  const response = await fetch(`${serverUrl}/internal/session/open`, {",
    "    method: 'POST',",
    "    headers: {",
    "      authorization: `Bearer ${authToken}`,",
    "      'content-type': 'application/json',",
    "    },",
    "    body: JSON.stringify({",
    "      hostId,",
    "      hostName,",
    "      hostType: 'ephemeral',",
    "      instanceId: randomUUID(),",
    "      protocolVersion,",
    "    }),",
    "  });",
    "",
    "  if (!response.ok) {",
    "    const body = await response.text();",
    "    throw new Error(`Session open failed with ${response.status}: ${body}`);",
    "  }",
    "}",
    "",
    "async function connectWithRetry() {",
    "  for (let attempt = 1; attempt <= maxConnectAttempts; attempt += 1) {",
    "    try {",
    "      await openSession();",
    "      console.log('session-opened');",
    "      return;",
    "    } catch (error) {",
    "      const message = error instanceof Error ? error.message : String(error);",
    "      if (attempt === maxConnectAttempts) {",
    "        throw new Error(`Session open failed after ${maxConnectAttempts} attempts: ${message}`);",
    "      }",
    "      const retryMs = Math.min(baseRetryMs * attempt, maxRetryMs);",
    "      console.error(`Session open failed, retrying in ${retryMs}ms (${attempt}/${maxConnectAttempts}): ${message}`);",
    "      await sleep(retryMs);",
    "    }",
    "  }",
    "}",
    "",
    "const server = createServer((request, response) => {",
    "  if (request.url === healthPath) {",
    "    response.writeHead(200, { 'content-type': 'text/plain' });",
    "    response.end('ok');",
    "    return;",
    "  }",
    "",
    "  response.writeHead(404);",
    "  response.end();",
    "});",
    "",
    "server.listen(healthPort, () => {",
    "  console.log('health-ready');",
    "  void connectWithRetry().catch((error) => {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    console.error(`Session open exhausted retries: ${message}`);",
    "    process.exit(1);",
    "  });",
    "});",
    "",
    "process.on('SIGTERM', () => {",
    "  server.close(() => process.exit(0));",
    "});",
  ].join("\n");
}
